"""empty message

Revision ID: 2c7aa70b6733
Revises: 6d6a855f7ede
Create Date: 2022-12-01 08:55:35.214262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7aa70b6733'
down_revision = '6d6a855f7ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanya', 'googleuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanya', sa.Column('googleuid', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
