"""empty message

Revision ID: 7087b80e8072
Revises: 
Create Date: 2022-11-30 08:59:02.455493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7087b80e8072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('pathname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bahtsul',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('isi', sa.String(length=255), nullable=False),
    sa.Column('gambar_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatwa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isi', sa.String(length=255), nullable=False),
    sa.Column('gambar_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanya',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('googleuid', sa.String(length=100), nullable=False),
    sa.Column('isi', sa.String(length=1500), nullable=False),
    sa.Column('gambar_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isi', sa.String(length=255), nullable=False),
    sa.Column('tanya_id', sa.BigInteger(), nullable=True),
    sa.Column('gambar_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gambar_id'], ['gambar.id'], ),
    sa.ForeignKeyConstraint(['tanya_id'], ['tanya.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('tanya')
    op.drop_table('fatwa')
    op.drop_table('bahtsul')
    op.drop_table('gambar')
    # ### end Alembic commands ###
